# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 20:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('door_no', models.CharField(blank=True, max_length=6)),
                ('street', models.CharField(blank=True, max_length=50)),
                ('village', models.CharField(max_length=50)),
                ('town', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(blank=True, default=b'', max_length=20)),
                ('pincode', models.DecimalField(decimal_places=0, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Bids',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_datetime', models.DateTimeField()),
                ('confirmation_datetime', models.DateTimeField()),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Demands',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('delivery_datetime', models.DateTimeField()),
                ('bid_end_datetime', models.DateTimeField()),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FarmProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='farmConnect.Address')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=3, max_digits=8)),
                ('longitude', models.DecimalField(decimal_places=3, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(max_length=1)),
                ('bid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='farmConnect.Bids')),
            ],
        ),
        migrations.CreateModel(
            name='Produce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('name_en', models.CharField(max_length=15, null=True)),
                ('name_ta', models.CharField(max_length=15, null=True)),
                ('pic', models.FileField(default=b'produce_pictures/empty.png', null=True, upload_to=b'produce_pictures')),
            ],
        ),
        migrations.CreateModel(
            name='ProduceCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('name_en', models.CharField(max_length=15, null=True)),
                ('name_ta', models.CharField(max_length=15, null=True)),
                ('pic', models.FileField(default=b'category_pictures/empty.png', null=True, upload_to=b'category_pictures')),
            ],
        ),
        migrations.CreateModel(
            name='StoreProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='farmConnect.Address')),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='farmConnect.Location')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SupportedLanguages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_name', models.CharField(max_length=40)),
                ('language_iso_code', models.CharField(max_length=3)),
                ('iso_format', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='TransportLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('log', models.CharField(max_length=300)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmConnect.Location')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmConnect.Orders')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(default=b'en', max_length=3)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
                ('user_type', models.CharField(blank=True, max_length=1)),
                ('address', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='farmConnect.Address')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='produce',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmConnect.ProduceCategory'),
        ),
        migrations.AddField(
            model_name='farmprofile',
            name='location',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='farmConnect.Location'),
        ),
        migrations.AddField(
            model_name='farmprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='demands',
            name='produce',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmConnect.Produce'),
        ),
        migrations.AddField(
            model_name='bids',
            name='demand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmConnect.Demands'),
        ),
        migrations.AddField(
            model_name='bids',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
